### ISSUE TITLE
test: only call unit tests when files are changed in the relevant service

### ISSUE THREAD

**Issue by jdhoffa** [RMI/pbtar#84]
I think this is probably a good idea. 

Something like:
``` yml
name: Test API Service

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
  pull_request:
    branches:
      - main
    paths:
      - 'api/**'
```

We don't need to be running _all_ unit tests, when only files in one service are actually being touched. 
Curious for folks' thoughts on this.
